// Katalog předmětů a nepřátel.
//
// Vytaženo z frontend/js/game.js, aby to server mohl uložit do
// databáze a admin editovat. Slouží jen k prvnímu naplnění —
// od té chvíle platí, co je v databázi.
const PREDMETY = [
  {
    "id": "w0",
    "nazev": "Wood Sword",
    "skupina": "weapons",
    "ikona": "🪵",
    "kvalita": "common",
    "klic_vlastnosti": "strength",
    "hodnota": 2,
    "cena": 25,
    "poskozeni_od": 2,
    "poskozeni_do": 4,
    "popis_statu": "2-4 poškození",
    "povoleno": true
  },
  {
    "id": "w1",
    "nazev": "Bronzový Meč",
    "skupina": "weapons",
    "ikona": "🗡️",
    "kvalita": "common",
    "klic_vlastnosti": "strength",
    "hodnota": 6,
    "cena": 100,
    "poskozeni_od": 7,
    "poskozeni_do": 12,
    "popis_statu": "7-12 poškození",
    "povoleno": true
  },
  {
    "id": "w2",
    "nazev": "Železné Kopí",
    "skupina": "weapons",
    "ikona": "🔱",
    "kvalita": "uncommon",
    "klic_vlastnosti": "strength",
    "hodnota": 12,
    "cena": 220,
    "poskozeni_od": 14,
    "poskozeni_do": 22,
    "popis_statu": "14-22 poškození",
    "povoleno": true
  },
  {
    "id": "w3",
    "nazev": "Ocelová Kosa",
    "skupina": "weapons",
    "ikona": "⚔️",
    "kvalita": "rare",
    "klic_vlastnosti": "strength",
    "hodnota": 20,
    "cena": 450,
    "poskozeni_od": 24,
    "poskozeni_do": 36,
    "popis_statu": "24-36 poškození",
    "povoleno": true
  },
  {
    "id": "w4",
    "nazev": "Meč Achillea",
    "skupina": "weapons",
    "ikona": "🌟",
    "kvalita": "epic",
    "klic_vlastnosti": "strength",
    "hodnota": 35,
    "cena": 900,
    "poskozeni_od": 42,
    "poskozeni_do": 62,
    "popis_statu": "42-62 poškození",
    "povoleno": true
  },
  {
    "id": "w5",
    "nazev": "Oštěp Artemidy",
    "skupina": "weapons",
    "ikona": "🔱",
    "kvalita": "rare",
    "klic_vlastnosti": "strength",
    "hodnota": 18,
    "cena": 380,
    "poskozeni_od": 20,
    "poskozeni_do": 31,
    "popis_statu": "20-31 poškození",
    "povoleno": true
  },
  {
    "id": "w6",
    "nazev": "Bojová Sekera",
    "skupina": "weapons",
    "ikona": "🪓",
    "kvalita": "uncommon",
    "klic_vlastnosti": "strength",
    "hodnota": 15,
    "cena": 290,
    "poskozeni_od": 17,
    "poskozeni_do": 29,
    "popis_statu": "17-29 poškození",
    "povoleno": true
  },
  {
    "id": "w7",
    "nazev": "Ocelový Meč",
    "skupina": "weapons",
    "ikona": "⚔️",
    "kvalita": "rare",
    "klic_vlastnosti": "strength",
    "hodnota": 20,
    "cena": 430,
    "poskozeni_od": 22,
    "poskozeni_do": 34,
    "popis_statu": "22-34 poškození",
    "povoleno": true
  },
  {
    "id": "a1",
    "nazev": "Kožená Zbroj",
    "skupina": "armor",
    "ikona": "🧥",
    "kvalita": "common",
    "klic_vlastnosti": "defense",
    "hodnota": 6,
    "cena": 90,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+6 Obrana",
    "povoleno": true
  },
  {
    "id": "a2",
    "nazev": "Bronzová Zbroj",
    "skupina": "armor",
    "ikona": "🛡️",
    "kvalita": "uncommon",
    "klic_vlastnosti": "defense",
    "hodnota": 14,
    "cena": 200,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+14 Obrana",
    "povoleno": true
  },
  {
    "id": "a3",
    "nazev": "Athénin Štít",
    "skupina": "armor",
    "ikona": "⛨",
    "kvalita": "rare",
    "klic_vlastnosti": "defense",
    "hodnota": 25,
    "cena": 480,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+25 Obrana",
    "povoleno": true
  },
  {
    "id": "a4",
    "nazev": "Zbroj Spartana",
    "skupina": "armor",
    "ikona": "💠",
    "kvalita": "epic",
    "klic_vlastnosti": "defense",
    "hodnota": 40,
    "cena": 950,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+40 Obrana",
    "povoleno": true
  },
  {
    "id": "a5",
    "nazev": "Plátěná Suknice",
    "skupina": "armor",
    "ikona": "🥋",
    "kvalita": "common",
    "klic_vlastnosti": "defense",
    "hodnota": 4,
    "cena": 60,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "a6",
    "nazev": "Kožich Barbarův",
    "skupina": "armor",
    "ikona": "🧥",
    "kvalita": "common",
    "klic_vlastnosti": "defense",
    "hodnota": 6,
    "cena": 110,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "a7",
    "nazev": "Zbroj Hraničáře",
    "skupina": "armor",
    "ikona": "🥼",
    "kvalita": "uncommon",
    "klic_vlastnosti": "agility",
    "hodnota": 9,
    "cena": 210,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "a13",
    "nazev": "Bronzový Krunýř",
    "skupina": "armor",
    "ikona": "🛡️",
    "kvalita": "uncommon",
    "klic_vlastnosti": "defense",
    "hodnota": 11,
    "cena": 260,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "a8",
    "nazev": "Šupinová Zbroj",
    "skupina": "armor",
    "ikona": "🐉",
    "kvalita": "rare",
    "klic_vlastnosti": "defense",
    "hodnota": 15,
    "cena": 410,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "a9",
    "nazev": "Stříbrná Zbroj",
    "skupina": "armor",
    "ikona": "⚪",
    "kvalita": "rare",
    "klic_vlastnosti": "defense",
    "hodnota": 18,
    "cena": 520,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "a10",
    "nazev": "Zbroj Olympu",
    "skupina": "armor",
    "ikona": "✨",
    "kvalita": "epic",
    "klic_vlastnosti": "defense",
    "hodnota": 24,
    "cena": 820,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "a11",
    "nazev": "Zbroj Persefony",
    "skupina": "armor",
    "ikona": "🔮",
    "kvalita": "epic",
    "klic_vlastnosti": "intelligence",
    "hodnota": 26,
    "cena": 900,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "a12",
    "nazev": "Zbroj Poseidona",
    "skupina": "armor",
    "ikona": "🌊",
    "kvalita": "epic",
    "klic_vlastnosti": "defense",
    "hodnota": 28,
    "cena": 980,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "h1",
    "nazev": "Korintská Helma",
    "skupina": "armor_extra",
    "ikona": "⛑️",
    "kvalita": "uncommon",
    "klic_vlastnosti": "defense",
    "hodnota": 8,
    "cena": 150,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+8 Obrana",
    "povoleno": true
  },
  {
    "id": "h2",
    "nazev": "Helma Heros",
    "skupina": "armor_extra",
    "ikona": "👑",
    "kvalita": "rare",
    "klic_vlastnosti": "defense",
    "hodnota": 16,
    "cena": 320,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+16 Obrana",
    "povoleno": true
  },
  {
    "id": "h3",
    "nazev": "Otlučená Přilba",
    "skupina": "armor_extra",
    "ikona": "⛑️",
    "kvalita": "common",
    "klic_vlastnosti": "defense",
    "hodnota": 3,
    "cena": 45,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "h4",
    "nazev": "Kožená Čapka",
    "skupina": "armor_extra",
    "ikona": "🧢",
    "kvalita": "common",
    "klic_vlastnosti": "defense",
    "hodnota": 5,
    "cena": 80,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "h5",
    "nazev": "Helma Poutníka",
    "skupina": "armor_extra",
    "ikona": "🪖",
    "kvalita": "uncommon",
    "klic_vlastnosti": "skill",
    "hodnota": 8,
    "cena": 180,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "h6",
    "nazev": "Helma Setníka",
    "skupina": "armor_extra",
    "ikona": "🎖️",
    "kvalita": "rare",
    "klic_vlastnosti": "defense",
    "hodnota": 13,
    "cena": 340,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "h7",
    "nazev": "Helma Válečníka",
    "skupina": "armor_extra",
    "ikona": "⚔️",
    "kvalita": "rare",
    "klic_vlastnosti": "strength",
    "hodnota": 15,
    "cena": 420,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "h8",
    "nazev": "Helma Áreova",
    "skupina": "armor_extra",
    "ikona": "👑",
    "kvalita": "epic",
    "klic_vlastnosti": "strength",
    "hodnota": 22,
    "cena": 760,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "zbroj",
    "povoleno": true
  },
  {
    "id": "g1",
    "nazev": "Kožené Rukavice",
    "skupina": "armor_extra",
    "ikona": "🥊",
    "kvalita": "common",
    "klic_vlastnosti": "strength",
    "hodnota": 5,
    "cena": 80,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+5 Síla",
    "povoleno": true
  },
  {
    "id": "g3",
    "nazev": "Bronzové Rukavice",
    "skupina": "armor_extra",
    "ikona": "🥊",
    "kvalita": "uncommon",
    "klic_vlastnosti": "strength",
    "hodnota": 9,
    "cena": 170,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+9 Síla",
    "povoleno": true
  },
  {
    "id": "g2",
    "nazev": "Železné Rukavice",
    "skupina": "armor_extra",
    "ikona": "👊",
    "kvalita": "uncommon",
    "klic_vlastnosti": "strength",
    "hodnota": 12,
    "cena": 200,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+12 Síla",
    "povoleno": true
  },
  {
    "id": "g4",
    "nazev": "Rukavice Titána",
    "skupina": "armor_extra",
    "ikona": "👊",
    "kvalita": "epic",
    "klic_vlastnosti": "strength",
    "hodnota": 26,
    "cena": 640,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+26 Síla",
    "povoleno": true
  },
  {
    "id": "b1",
    "nazev": "Běžné Boty",
    "skupina": "armor_extra",
    "ikona": "👟",
    "kvalita": "common",
    "klic_vlastnosti": "agility",
    "hodnota": 4,
    "cena": 70,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+4 Hbitost",
    "povoleno": true
  },
  {
    "id": "b4",
    "nazev": "Bronzové Holeně",
    "skupina": "armor_extra",
    "ikona": "🥾",
    "kvalita": "uncommon",
    "klic_vlastnosti": "agility",
    "hodnota": 8,
    "cena": 160,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+8 Hbitost",
    "povoleno": true
  },
  {
    "id": "b2",
    "nazev": "Hermovy Boty",
    "skupina": "armor_extra",
    "ikona": "🥾",
    "kvalita": "rare",
    "klic_vlastnosti": "agility",
    "hodnota": 10,
    "cena": 180,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+10 Hbitost",
    "povoleno": true
  },
  {
    "id": "b5",
    "nazev": "Ocelové Holeně",
    "skupina": "armor_extra",
    "ikona": "🥾",
    "kvalita": "rare",
    "klic_vlastnosti": "agility",
    "hodnota": 16,
    "cena": 340,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+16 Hbitost",
    "povoleno": true
  },
  {
    "id": "b6",
    "nazev": "Boty Nesmrtelných",
    "skupina": "armor_extra",
    "ikona": "🥾",
    "kvalita": "epic",
    "klic_vlastnosti": "agility",
    "hodnota": 28,
    "cena": 720,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+28 Hbitost",
    "povoleno": true
  },
  {
    "id": "b3",
    "nazev": "Kožený Pás",
    "skupina": "armor_extra",
    "ikona": "🔗",
    "kvalita": "common",
    "klic_vlastnosti": "defense",
    "hodnota": 3,
    "cena": 60,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+3 Obrana",
    "povoleno": true
  },
  {
    "id": "r1",
    "nazev": "Otlučený Prsten",
    "skupina": "rings",
    "ikona": "💍",
    "kvalita": "common",
    "klic_vlastnosti": "agility",
    "hodnota": 4,
    "cena": 40,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": null,
    "povoleno": true
  },
  {
    "id": "r2",
    "nazev": "Měděný Kroužek",
    "skupina": "rings",
    "ikona": "💍",
    "kvalita": "common",
    "klic_vlastnosti": "defense",
    "hodnota": 6,
    "cena": 75,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": null,
    "povoleno": true
  },
  {
    "id": "r3",
    "nazev": "Prsten Poutníka",
    "skupina": "rings",
    "ikona": "💍",
    "kvalita": "uncommon",
    "klic_vlastnosti": "agility",
    "hodnota": 9,
    "cena": 140,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": null,
    "povoleno": true
  },
  {
    "id": "r4",
    "nazev": "Stříbrný Prsten",
    "skupina": "rings",
    "ikona": "💍",
    "kvalita": "uncommon",
    "klic_vlastnosti": "intelligence",
    "hodnota": 12,
    "cena": 210,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": null,
    "povoleno": true
  },
  {
    "id": "r5",
    "nazev": "Prsten Věštkyně",
    "skupina": "rings",
    "ikona": "💍",
    "kvalita": "rare",
    "klic_vlastnosti": "intelligence",
    "hodnota": 18,
    "cena": 340,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": null,
    "povoleno": true
  },
  {
    "id": "r6",
    "nazev": "Onyxový Prsten",
    "skupina": "rings",
    "ikona": "💍",
    "kvalita": "rare",
    "klic_vlastnosti": "defense",
    "hodnota": 22,
    "cena": 460,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": null,
    "povoleno": true
  },
  {
    "id": "r7",
    "nazev": "Prsten Legionáře",
    "skupina": "rings",
    "ikona": "💍",
    "kvalita": "epic",
    "klic_vlastnosti": "strength",
    "hodnota": 30,
    "cena": 700,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": null,
    "povoleno": true
  },
  {
    "id": "r8",
    "nazev": "Prsten Sudiček",
    "skupina": "rings",
    "ikona": "💍",
    "kvalita": "epic",
    "klic_vlastnosti": "intelligence",
    "hodnota": 38,
    "cena": 980,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": null,
    "povoleno": true
  },
  {
    "id": "m1",
    "nazev": "Hermův Amulet",
    "skupina": "jewelry",
    "ikona": "💍",
    "kvalita": "uncommon",
    "klic_vlastnosti": "agility",
    "hodnota": 8,
    "cena": 180,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+8 Hbitost",
    "povoleno": true
  },
  {
    "id": "m2",
    "nazev": "Apollónův Prsten",
    "skupina": "jewelry",
    "ikona": "💎",
    "kvalita": "uncommon",
    "klic_vlastnosti": "intelligence",
    "hodnota": 10,
    "cena": 220,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+10 Intel.",
    "povoleno": true
  },
  {
    "id": "m4",
    "nazev": "Afroditin Amulet",
    "skupina": "jewelry",
    "ikona": "✨",
    "kvalita": "rare",
    "klic_vlastnosti": "agility",
    "hodnota": 12,
    "cena": 280,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+12 Hbitost",
    "povoleno": true
  },
  {
    "id": "m5",
    "nazev": "Zeusův Prsten",
    "skupina": "jewelry",
    "ikona": "⚡",
    "kvalita": "rare",
    "klic_vlastnosti": "strength",
    "hodnota": 15,
    "cena": 400,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+15 Síla",
    "povoleno": true
  },
  {
    "id": "p1",
    "nazev": "Malý Lektvar",
    "skupina": "potions",
    "ikona": "🧪",
    "kvalita": "common",
    "klic_vlastnosti": "health",
    "hodnota": 30,
    "cena": 25,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+30 HP",
    "povoleno": true
  },
  {
    "id": "p2",
    "nazev": "Střední Lektvar",
    "skupina": "potions",
    "ikona": "⚗️",
    "kvalita": "uncommon",
    "klic_vlastnosti": "health",
    "hodnota": 80,
    "cena": 60,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+80 HP",
    "povoleno": true
  },
  {
    "id": "p3",
    "nazev": "Ambrózie Bohů",
    "skupina": "potions",
    "ikona": "🍯",
    "kvalita": "rare",
    "klic_vlastnosti": "health",
    "hodnota": 200,
    "cena": 150,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+200 HP",
    "povoleno": true
  },
  {
    "id": "p4",
    "nazev": "Nektár Olimpu",
    "skupina": "potions",
    "ikona": "🥛",
    "kvalita": "epic",
    "klic_vlastnosti": "health",
    "hodnota": 300,
    "cena": 280,
    "poskozeni_od": null,
    "poskozeni_do": null,
    "popis_statu": "+300 HP",
    "povoleno": true
  }
];

const NEPRATELE = [
  {
    "klic": "chram_0",
    "jmeno": "Orčí poskok",
    "obrazek": "monsters/ork-poskok.jpg",
    "lokace": "chram",
    "lokace_nazev": "Orčí Les",
    "uroven_lokace": 1,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "chram_1",
    "jmeno": "Naštvaný ork",
    "obrazek": "monsters/ork-nastvany.jpg",
    "lokace": "chram",
    "lokace_nazev": "Orčí Les",
    "uroven_lokace": 1,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "chram_2",
    "jmeno": "Orčí šamanka",
    "obrazek": "monsters/ork-samanka.jpg",
    "lokace": "chram",
    "lokace_nazev": "Orčí Les",
    "uroven_lokace": 1,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "chram_3",
    "jmeno": "Orčí velitel",
    "obrazek": "monsters/ork-velitel.jpg",
    "lokace": "chram",
    "lokace_nazev": "Orčí Les",
    "uroven_lokace": 1,
    "poradi": 3,
    "povoleno": true
  },
  {
    "klic": "les_0",
    "jmeno": "Lesní Vlk",
    "obrazek": "wolf",
    "lokace": "les",
    "lokace_nazev": "Zelený les",
    "uroven_lokace": 8,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "les_1",
    "jmeno": "Masožravka",
    "obrazek": "plant",
    "lokace": "les",
    "lokace_nazev": "Zelený les",
    "uroven_lokace": 8,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "les_2",
    "jmeno": "Zelený Had",
    "obrazek": "snake",
    "lokace": "les",
    "lokace_nazev": "Zelený les",
    "uroven_lokace": 8,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "les_3",
    "jmeno": "Starý Treant",
    "obrazek": "treant",
    "lokace": "les",
    "lokace_nazev": "Zelený les",
    "uroven_lokace": 8,
    "poradi": 3,
    "povoleno": true
  },
  {
    "klic": "vesnice_0",
    "jmeno": "Kostlivec Šermíř",
    "obrazek": "skeleton-swordfighter",
    "lokace": "vesnice",
    "lokace_nazev": "Zakletá vesnice",
    "uroven_lokace": 12,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "vesnice_1",
    "jmeno": "Kostlivec Lučištník",
    "obrazek": "skeleton-archer",
    "lokace": "vesnice",
    "lokace_nazev": "Zakletá vesnice",
    "uroven_lokace": 12,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "vesnice_2",
    "jmeno": "Kostlivec Zloděj",
    "obrazek": "skeleton-rogue",
    "lokace": "vesnice",
    "lokace_nazev": "Zakletá vesnice",
    "uroven_lokace": 12,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "vesnice_3",
    "jmeno": "Kostlivec Mág",
    "obrazek": "skeleton-mage",
    "lokace": "vesnice",
    "lokace_nazev": "Zakletá vesnice",
    "uroven_lokace": 12,
    "poradi": 3,
    "povoleno": true
  },
  {
    "klic": "pahorek_0",
    "jmeno": "Stín",
    "obrazek": "shadow",
    "lokace": "pahorek",
    "lokace_nazev": "Pahorek Smrti",
    "uroven_lokace": 16,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "pahorek_1",
    "jmeno": "Přízrak",
    "obrazek": "spirit",
    "lokace": "pahorek",
    "lokace_nazev": "Pahorek Smrti",
    "uroven_lokace": 16,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "pahorek_2",
    "jmeno": "Bánší",
    "obrazek": "banshee",
    "lokace": "pahorek",
    "lokace_nazev": "Pahorek Smrti",
    "uroven_lokace": 16,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "pahorek_3",
    "jmeno": "Oživlá Zbroj",
    "obrazek": "armor",
    "lokace": "pahorek",
    "lokace_nazev": "Pahorek Smrti",
    "uroven_lokace": 16,
    "poradi": 3,
    "povoleno": true
  },
  {
    "klic": "vandalove_0",
    "jmeno": "Rudý Skřítek",
    "obrazek": "red-imp",
    "lokace": "vandalove",
    "lokace_nazev": "Vesnice Vandalů",
    "uroven_lokace": 20,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "vandalove_1",
    "jmeno": "Černý Skřítek",
    "obrazek": "black-imp",
    "lokace": "vandalove",
    "lokace_nazev": "Vesnice Vandalů",
    "uroven_lokace": 20,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "vandalove_2",
    "jmeno": "Vandalský Troll",
    "obrazek": "troll",
    "lokace": "vandalove",
    "lokace_nazev": "Vesnice Vandalů",
    "uroven_lokace": 20,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "vandalove_3",
    "jmeno": "Náčelník Skřetů",
    "obrazek": "goblin",
    "lokace": "vandalove",
    "lokace_nazev": "Vesnice Vandalů",
    "uroven_lokace": 20,
    "poradi": 3,
    "povoleno": true
  },
  {
    "klic": "dul_0",
    "jmeno": "Důlní Pavouk",
    "obrazek": "spider",
    "lokace": "dul",
    "lokace_nazev": "Důl",
    "uroven_lokace": 24,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "dul_1",
    "jmeno": "Slizoun Hlubin",
    "obrazek": "slime",
    "lokace": "dul",
    "lokace_nazev": "Důl",
    "uroven_lokace": 24,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "dul_2",
    "jmeno": "Kamenný Golem",
    "obrazek": "golem",
    "lokace": "dul",
    "lokace_nazev": "Důl",
    "uroven_lokace": 24,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "dul_3",
    "jmeno": "Horský Troll",
    "obrazek": "troll",
    "lokace": "dul",
    "lokace_nazev": "Důl",
    "uroven_lokace": 24,
    "poradi": 3,
    "povoleno": true
  },
  {
    "klic": "teutoni_0",
    "jmeno": "Teutonský Válečník",
    "obrazek": "skeleton-swordfighter",
    "lokace": "teutoni",
    "lokace_nazev": "Tábor Teutonů",
    "uroven_lokace": 28,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "teutoni_1",
    "jmeno": "Železná Zbroj",
    "obrazek": "armor",
    "lokace": "teutoni",
    "lokace_nazev": "Tábor Teutonů",
    "uroven_lokace": 28,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "teutoni_2",
    "jmeno": "Bojový Gryf",
    "obrazek": "griffin",
    "lokace": "teutoni",
    "lokace_nazev": "Tábor Teutonů",
    "uroven_lokace": 28,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "teutoni_3",
    "jmeno": "Stín Velitele",
    "obrazek": "shadow",
    "lokace": "teutoni",
    "lokace_nazev": "Tábor Teutonů",
    "uroven_lokace": 28,
    "poradi": 3,
    "povoleno": true
  },
  {
    "klic": "koman_0",
    "jmeno": "Skalní Gryf",
    "obrazek": "griffin",
    "lokace": "koman",
    "lokace_nazev": "Hora Koman",
    "uroven_lokace": 32,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "koman_1",
    "jmeno": "Přízrak Vrcholu",
    "obrazek": "spirit",
    "lokace": "koman",
    "lokace_nazev": "Hora Koman",
    "uroven_lokace": 32,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "koman_2",
    "jmeno": "Ledový Troll",
    "obrazek": "troll",
    "lokace": "koman",
    "lokace_nazev": "Hora Koman",
    "uroven_lokace": 32,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "koman_3",
    "jmeno": "Skalní Golem",
    "obrazek": "golem",
    "lokace": "koman",
    "lokace_nazev": "Hora Koman",
    "uroven_lokace": 32,
    "poradi": 3,
    "povoleno": true
  },
  {
    "klic": "draci_0",
    "jmeno": "Drakonid",
    "obrazek": "snake",
    "lokace": "draci",
    "lokace_nazev": "Dračí ostatky",
    "uroven_lokace": 36,
    "poradi": 0,
    "povoleno": true
  },
  {
    "klic": "draci_1",
    "jmeno": "Mladý Drak",
    "obrazek": "dragon",
    "lokace": "draci",
    "lokace_nazev": "Dračí ostatky",
    "uroven_lokace": 36,
    "poradi": 1,
    "povoleno": true
  },
  {
    "klic": "draci_2",
    "jmeno": "Kostěný Šaman",
    "obrazek": "skeleton-mage",
    "lokace": "draci",
    "lokace_nazev": "Dračí ostatky",
    "uroven_lokace": 36,
    "poradi": 2,
    "povoleno": true
  },
  {
    "klic": "draci_3",
    "jmeno": "Prastarý Drak",
    "obrazek": "dragon",
    "lokace": "draci",
    "lokace_nazev": "Dračí ostatky",
    "uroven_lokace": 36,
    "poradi": 3,
    "povoleno": true
  }
];

module.exports = { PREDMETY, NEPRATELE };
